Update/chapter 4
Ackee-Blockchain/solana-handbook pull request #21
Opened 2024-09-23 14:39 UTC by hyckomatej

2024-09-25 09:09 UTC, lukacan requested changes

2024-09-26 18:10 UTC, hyckomatej commented on docs/handbook/chapter4/token-2022.md
> +Some of the mint extensions:
some of the extensions inside paper are not in the documentation https://spl.solana.com/token-2022.

2024-09-26 18:12 UTC, hyckomatej commented on docs/handbook/chapter4/token-2022.md
> +Some of the mint extensions:
but they are [here](https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/extension/mod.rs). should i add them as well?

2024-09-29 18:24 UTC, lukacan requested changes
private communication

2024-10-05 12:02 UTC, lukacan commented
@hyckomatej I made some small updates can you please check ?

2024-10-06 11:00 UTC, lukacan approved these changes

2024-10-06 11:00 UTC, merged